(defunc fizzbuzz (n) 
    (for i (in-range 1 n) 
        (if (= 0 (% i 15))
            (print "FizzBuzz") 
            (if (= 0 (% i 3)) 
                (print "Fizz") 
                (if (= 0 (% i 5)) 
                    (print "Buzz") 
                    (print i)
                )
            )
        )
    )
)

(fizzbuzz 5)